version: 2.1

jobs:
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["7c:77:4e:99:ca:46:c8:2d:31:73:32:cc:12:36:85:11"]      # Add ssh keys with fingerprint
      - attach_workspace:
          at: project/.circleci/ansible
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt configure-server.yml
         # Here's where you will add some code to rollback on failure                
workflows:
  default:
    jobs:
      - deploy-infrastructure
