version: 2.1

jobs:

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            cd .circleci/ansible
            ls -al inventory*
            cat inventory.txt
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text
            
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text >> inventory.txt
            cat inventory.txt

         # Here's where you will add some code to rollback on failure                
workflows:
  default:
    jobs:
      - deploy-infrastructure
